#!/usr/bin/env bash

if
  [[ -s "/home/parallels/.rvm/gems/ruby-2.1.5@global/environment" ]]
then
  source "/home/parallels/.rvm/gems/ruby-2.1.5@global/environment"
  exec bundle "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/parallels/.rvm/gems/ruby-2.1.5@global/environment'" >&2
  exit 1
fi
